Repository nninyeong/dream-card, pull requests merged in 2024-11, with the labels that each got.

#58 Feat/invitation: 청첩장 미리보기, 비공개 설정 시 보이지 않도록 구현
  src/app/api/.gitkeep
  src/app/api/revalidate/route.ts
  src/app/card/[id]/page.tsx
  src/components/attendance/AttendanceButton.tsx
  src/components/card/Account.tsx
  src/components/card/Greeting.tsx
  src/components/card/GuestInfo.tsx
  src/components/card/MainPhoto.tsx
  src/components/card/NavigationDetails.tsx
  src/components/card/PersonalInfoOnSharedCard.tsx
  src/components/card/StickerOnSharedCard.tsx
  src/components/card/WeddingGallery.tsx
  src/components/card/WeddingInfo.tsx
  src/components/create/preview/AccountPreView.tsx
  src/components/create/preview/GalleryPreview.tsx
  src/components/create/preview/GreetingPreview.tsx
  src/components/create/preview/GuestInfoPreview.tsx
  src/components/create/preview/MainPhotoPreView.tsx
  src/components/create/preview/NavigationDetailsPreview.tsx
  src/components/create/preview/PersonalInfoPreView.tsx
  src/components/create/preview/WeddingInfoPreView.tsx
  src/components/guestbook/GuestBook.tsx
  src/components/layouts/Navigation.tsx
  src/components/mypage/TogglePrivate.tsx
  src/hooks/invitation/useInvitationIdByPathname.ts
  src/types/invitationFormType.type.ts
  src/utils/myPage.ts
  src/utils/revalidateInvitation.ts
Labels: 새 기능

#59 Feat/mood keyword
  src/app/globals.css
  src/components/main/MoodKeyword.tsx
Labels: 스타일

#61 Feat/create review photo: 후기 작성 바텀시트 구현
  public/assets/images/icons/chevron-left.svg
  public/assets/images/icons/chevron-right.svg
  public/assets/images/icons/image-add.svg
  public/assets/images/icons/white-edit-contained-selceted.svg
  src/app/create/card/page.tsx
  src/app/review/[id]/page.tsx
  src/app/review/page.tsx
  src/app/review/write/page.tsx
  src/components/create/OnBoarding.tsx
  src/components/review/ReviewContentsBox.tsx
  src/components/review/ReviewForm.tsx
  src/components/review/ReviewSlide.tsx
  src/components/review/ReviewWriteBottomSheet.tsx
  src/components/review/ReviewWriteButton.tsx
  src/constants/viewHeight.ts
  src/lib/zod/reviewInputSchema.ts
Labels: 새 기능, 스타일

#68 Style/navigation: 네비게이션 영역 디자인 반영
  public/assets/images/icons/kakaomap.svg
  public/assets/images/icons/naver-map.svg
  public/assets/images/icons/selected-off.svg
  public/assets/images/icons/selected-on.svg
  public/assets/images/icons/tmap.svg
  src/components/card/NavigationDetails.tsx
  src/components/create/NavigationButtons.tsx
  src/components/create/NavigationDetailCard.tsx
  src/components/create/NavigationDetailInput.tsx
  src/components/guestbook/GuestBookCard.tsx
  src/components/map/MapView.tsx
Labels: 스타일

#74 style: 계산한 기기 innerHeight 적용
  src/constants/viewHeight.ts
Labels: 스타일

#73 style: 계좌번호 버튼 슬라이드식으로 변경
  src/components/create/AccountInput.tsx
  src/components/create/AccountModalPersonalBox.tsx
  src/utils/convertIndexToAccountLabel.ts
Labels: 스타일

#66 Feat/무한스크롤 refactor, reactDnD설치, gallerypreview에서 사진 개별삭제&supabaseStorage삭제
  package.json
  pnpm-lock.yaml
  src/app/create/card/page.tsx
  src/app/review/page.tsx
  src/components/card/WeddingGallery.tsx
  src/components/mypage/MyInvitationCard.tsx
  src/hooks/queries/invitation/useUpdateImages.ts
  src/hooks/queries/queryKeys.ts
  src/hooks/queries/review/useGetReview.ts
  src/types/database.type.ts
  src/types/invitationFormType.type.ts
  src/utils/getReview.ts
  src/utils/myPage.ts
  src/utils/uploadImg.ts
Labels: 새 기능, 리팩토링

#76 Feat/save main photo: 메인사진 영역을 이미지 한장으로 변환
  package.json
  pnpm-lock.yaml
  src/app/create/card/page.tsx
  src/components/card/MainPhoto.tsx
  src/components/create/preview/MainPhotoPreView.tsx
  src/utils/EventBus.ts
  src/utils/captureMainPhotoToPng.ts
Labels: 새 기능

#77 Feat/onboarding: 온보딩 화면 뒷배경 적용
  src/app/create/card/page.tsx
  src/components/create/OnBoarding.tsx
Labels: 리팩토링, 스타일

#81 Style/toggle motion : input form 열고 닫는 모션 추가
  public/assets/images/icons/chevron-left.svg
  public/assets/images/icons/chevron-right.svg
  src/app/create/card/page.tsx
  src/components/create/DecorateImageTypeComponent.tsx
  src/components/create/GalleryInput.tsx
  src/components/create/GreetingInput.tsx
  src/components/create/GuestInfoInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/create/MainViewInput.tsx
  src/components/create/NavigationDetailInput.tsx
Labels: 스타일

#83 Style/fixed nav
  public/assets/images/branding/mood-preset-01.png
  src/app/page.tsx
  src/components/ui/FixedQuickLink.tsx
  src/components/ui/LinkToCreateCard.tsx
  src/constants/notiflixInitValues.ts
  tailwind.config.ts
Labels: 스타일

#84 feat: 계좌번호 모달 복사하기 클릭시 모달 닫기 및 빈값 검사
  src/components/create/AccountModalPersonalBox.tsx
  src/components/create/modal/AccountModal.tsx
Labels: 새 기능

#92 Fix/sticker fetch: 스티커 회전 기능 추가
  src/components/create/stickerInput/Sticker.tsx
  src/components/create/stickerInput/StickerSlot.tsx
  src/constants/invitationStickers.ts
  src/types/invitationFormType.type.ts
  src/utils/calculate/calculateAngle.ts
  src/utils/calculate/calculateComponentRotation.ts
  src/utils/calculate/calculateRelativePosition.ts
Labels: 새 기능

#91 Feat/gallery [gallery 이미지 위치 Drag&Drop변경, 후기 아코디언, 공유메세지 변경]
  src/app/layout.tsx
  src/components/card/WeddingGallery.tsx
  src/components/create/RenderOrderInput.tsx
  src/components/gallery/GalleryImage.tsx
  src/components/gallery/GalleryView.tsx
  src/components/layouts/DndProvider.tsx
  src/components/mypage/MyInvitationCard.tsx
  src/components/mypage/MyPageNavigatorList.tsx
  src/hooks/queries/mypage/useMypage.ts
  src/hooks/queries/queryKeys.ts
  src/hooks/queries/review/useGetReview.ts
  src/provider/reviewBottomSheetProvider.tsx
  src/utils/convert/convertOrderToComponent.tsx
  src/utils/uploadImg.ts
Labels: 새 기능, 리팩토링

#96 feat:미리보기용 갤러리완성&스타일수정
  src/components/card/WeddingGallery.tsx
  src/components/gallery/GalleryView.tsx
Labels: 새 기능, 스타일

#104 Feat/ quillEditor정렬기능, style/ 메인화면입력페이지, 갤러리페이지, 인사말 페이지 스타일적용 , 글꼴저장된 것 미리보기페이지에 반영
  src/app/card/[id]/page.tsx
  src/app/globals.css
  src/components/card/Greeting.tsx
  src/components/card/MainPhoto.tsx
  src/components/card/WeddingGallery.tsx
  src/components/create/GalleryInput.tsx
  src/components/create/GreetingInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/create/TextEditor.tsx
  src/components/gallery/GalleryButton.tsx
  src/components/gallery/GalleryView.tsx
Labels: 새 기능, 스타일

#109 Feat/shared card: 스티커 인풋/공유용 레이아웃 수정
  public/assets/images/icons/equals.webp
  src/app/create/card/page.tsx
  src/components/card/Account.tsx
  src/components/card/Greeting.tsx
  src/components/card/GuestInfo.tsx
  src/components/card/MainPhoto.tsx
  src/components/card/NavigationDetails.tsx
  src/components/card/PersonalInfoOnSharedCard.tsx
  src/components/card/WeddingGallery.tsx
  src/components/card/WeddingInfo.tsx
  src/components/create/DraggableRenderOrder.tsx
  src/components/create/RenderOrderInput.tsx
  src/components/create/WeddingInfoInput.tsx
  src/components/create/preview/MainPhotoPreView.tsx
  src/components/guestbook/GuestBookCard.tsx
  src/constants/componentTypes.ts
  src/constants/invitaionDefaultValue.ts
  src/constants/invitationViewOrder.tsx
  src/types/invitationFormType.type.ts
  src/utils/convert/convertOrderToComponent.tsx
  src/utils/date/dayToKst.ts
  src/utils/date/getDayOfWeek.ts
Labels: 새 기능, 스타일

#112 Fix: 온보딩 높이, 미리보기 배경색 적용, 입력창 정렬, 미리보기 수정
  src/app/card/[id]/page.tsx
  src/app/create/card/page.tsx
  src/components/create/OnBoarding.tsx
  src/constants/viewHeight.ts
  src/types/invitationFormType.type.ts
  src/utils/convert/invitaitonTypeConvert.ts
Labels: 새 기능, 스타일

#118 style: 온보딩 너비 제한
  src/app/create/card/page.tsx
  src/app/layout.tsx
  src/app/review/[id]/page.tsx
  src/app/review/page.tsx
  src/components/create/OnBoarding.tsx
  src/components/layouts/Header.tsx
  src/constants/screenSize.ts
  src/constants/viewHeight.ts
Labels: 리팩토링, 스타일

#129 Fix/layout: 파비콘 설정, 레이아웃 분리
  src/app/(defaultLayout)/layout.tsx
  src/app/(defaultLayout)/mypage/page.tsx
  src/app/(defaultLayout)/page.tsx
  src/app/(defaultLayout)/review/[id]/page.tsx
  src/app/(defaultLayout)/review/images/page.tsx
  src/app/(defaultLayout)/review/page.tsx
  src/app/(defaultLayout)/signin/page.tsx
  src/app/(noLayout)/card/[id]/page.tsx
  src/app/(noLayout)/create/card/page.tsx
  src/app/favicon.ico
  src/app/icon.ico
  src/app/layout.tsx
  src/middleware.ts
Labels: 리팩토링

#130 Style/invitation main text: 메인사진 대표문구 위치 변경
  src/components/card/MainPhoto.tsx
  src/components/create/preview/MainPhotoPreView.tsx
  src/utils/convert/convertOrderToComponent.tsx
Labels: 스타일

#131 fix: client 환경에 세팅해야하는 옵션들 정리
  src/app/layout.tsx
  src/components/layouts/Navigation.tsx
  src/components/layouts/SetScreenHeight.tsx
  src/utils/settings/InitClientSettings.tsx
Labels: 버그

#132 fix: 제작페이지에서 방명록, 참석여부 수정 불가능하게 변경
  src/components/attendance/AttendanceButton.tsx
  src/components/attendance/AttendanceModal.tsx
  src/components/attendance/PreviewShowAttendanceModal.tsx
  src/components/create/EventStatus.tsx
  src/components/guestbook/CreateGuestBook.tsx
  src/components/guestbook/DeleteGuestBookAccordion.tsx
  src/components/guestbook/GuestBook.tsx
  src/components/guestbook/GuestBookCard.tsx
  src/hooks/attendance/useAttendanceModal.ts
  src/hooks/guestbook/useCreateGuestBookInput.ts
  src/hooks/guestbook/useDeleteGuestBookInput.ts
  src/hooks/invitation/useInvitationIdByPathname.ts
Labels: 리팩토링

#133 Feat/sticker mouse: 스티커 마우스 이벤트 추가, 기능 변경사항 반영
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/components/card/MainPhoto.tsx
  src/components/card/StickerOnSharedCard.tsx
  src/components/create/stickerInput/Sticker.tsx
  src/components/create/stickerInput/StickerSlot.tsx
  src/constants/invitationStickers/classicStickers.ts
  src/constants/invitationStickers/floralStickers.ts
  src/constants/invitationStickers/modernStickers.ts
  src/constants/invitationStickers/romanticStickers.ts
  src/constants/invitationStickers/rusticStickers.ts
  src/constants/invitationStickers/simpleStickers.ts
  src/hooks/invitation/sticker/useStickerMove.ts
  src/hooks/invitation/sticker/useStickerTransform.ts
  src/types/invitationFormType.type.ts
  src/utils/calculate/calculateAngle.ts
  src/utils/calculate/calculateDistance.ts
  src/utils/calculate/calculateRelativePosition.ts
Labels: 리팩토링, 스타일

#135 style: 소셜로그인 디자인 변경사항 반영
  public/assets/images/button/googleIcon.svg
  public/assets/images/button/kakaoIcon.svg
  public/assets/images/button/naverIcon.svg
  public/assets/images/icons/icon-google.webp
  public/assets/images/icons/icon-kakao.webp
  public/assets/images/icons/icon-naver.webp
  src/app/(defaultLayout)/signin/page.tsx
Labels: 스타일

#137 Feat/scroll structure - 스크롤로 읽히지 않던 input을 다시 감지하도록 수정
  src/app/(noLayout)/create/card/page.tsx
  src/components/create/preview/GuestInfoPreview.tsx
  src/constants/invitationViewOrder.tsx
  src/hooks/observer/useIntersectionObserver.ts
Labels: 버그

#139 Feat/open graph: 오픈그래프 이미지, 메타데이터 설정
  public/assets/images/branding/2D-logo.png
  src/app/(noLayout)/card/[id]/page.tsx
  src/app/layout.tsx
  src/app/opengraph-image.tsx
  src/constants/invitaionDefaultValue.ts
Labels: 새 기능

#140 bugfix: user_metadata 접근 에러 방지
  src/components/main/Carousel.tsx
Labels: 버그

#136 Feat/fontInput생성, 컬러팔레트 컴포넌트분리, css, preview화면 반영, (폰트크기, 색상변경)
  src/app/(noLayout)/card/[id]/page.tsx
  src/app/(noLayout)/create/card/page.tsx
  src/app/globals.css
  src/components/attendance/AttendanceModal.tsx
  src/components/card/Account.tsx
  src/components/card/Greeting.tsx
  src/components/card/GuestInfo.tsx
  src/components/card/MainPhoto.tsx
  src/components/card/NavigationDetails.tsx
  src/components/card/PersonalInfoOnSharedCard.tsx
  src/components/card/WeddingGallery.tsx
  src/components/card/WeddingInfo.tsx
  src/components/create/BackgroundColorInput.tsx
  src/components/create/ColorPalette.tsx
  src/components/create/ColorPaletteModal.tsx
  src/components/create/CreateGuestInfo.tsx
  src/components/create/FontInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/create/NavigationButtons.tsx
  src/components/create/NavigationDetailCard.tsx
  src/components/create/modal/AccountModal.tsx
  src/components/create/preview/AccountPreView.tsx
  src/components/create/preview/GalleryPreview.tsx
  src/components/create/preview/GreetingPreview.tsx
  src/components/create/preview/GuestInfoPreview.tsx
  src/components/create/preview/MainPhotoPreView.tsx
  src/components/create/preview/NavigationDetailsPreview.tsx
  src/components/create/preview/PersonalInfoCard.tsx
  src/components/create/preview/PersonalInfoPreView.tsx
  src/components/create/preview/WeddingInfoPreView.tsx
  src/components/ddaycounter/DdayCounter.tsx
  src/components/gallery/GalleryView.tsx
  src/components/guestbook/GuestBook.tsx
  src/components/guestbook/GuestBookCard.tsx
  src/components/icons/MessageIcon.tsx
  src/components/icons/PhoneIcon.tsx
  src/constants/invitaionDefaultValue.ts
  src/constants/invitationViewOrder.tsx
  src/store/useFontStore.ts
  src/types/database.type.ts
  src/types/invitationFormType.type.ts
  src/types/mainFont.type.ts
  src/utils/convert/convertOrderToComponent.tsx
  src/utils/convert/invitaitonTypeConvert.ts
Labels: 새 기능, 리팩토링, 스타일

#148 Feat/not found: notFound, error.tsx 설정
  .gitignore
  next.config.mjs
  package.json
  pnpm-lock.yaml
  public/assets/images/card/noCard.webp
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  src/app/api/sentry-example-api/route.ts
  src/app/error.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/components/errors/UnexpectedError.tsx
  src/instrumentation.ts
Labels: 새 기능

#162 Fix/card page bug: 청첩장 페이지 에러 처리
  src/app/(noLayout)/card/[id]/page.tsx
  src/components/create/MoodPresetInput.tsx
  src/components/create/StickerInput.tsx
  src/components/create/preview/MainPhotoPreView.tsx
Labels: 버그

#153 Style/address input: 주소입력창, 메인소개사진 최대너비 설정
  src/app/(defaultLayout)/page.tsx
  src/components/create/WeddingInfoInput.tsx
Labels: 스타일

#157 feat/ sitemap동적,정적설정, robot.txt설정 , feat/mypage 진척도현황 , 레이아웃완성
  package.json
  pnpm-lock.yaml
  public/assets/images/icons/download-02-selceted.webp
  public/assets/images/icons/link-icon.webp
  public/assets/images/icons/write.webp
  public/assets/images/icons/x-03.webp
  src/app/(defaultLayout)/mypage/page.tsx
  src/app/(noLayout)/card/[id]/page.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/create/FontInput.tsx
  src/components/create/GalleryInput.tsx
  src/components/mypage/MyInvitationCard.tsx
  src/constants/invitaionDefaultValue.ts
  src/store/useFontStore.ts
  src/types/invitationFormType.type.ts
  src/utils/calculateProgressPercentage.ts
  src/utils/convert/invitaitonTypeConvert.ts
  src/utils/uniqueFile.ts
  src/utils/uploadImg.ts
Labels: 새 기능

#171 Style/auth desktop design: 회원가입/로그인 데스크톱 시안 반영
  public/assets/fonts/HakgyoansimWoojuR.ttf
  src/app/(defaultLayout)/signin/page.tsx
  src/app/(defaultLayout)/signup/page.tsx
  src/app/globals.css
  src/app/signup/page.tsx
  src/components/auth/AuthForm.tsx
  src/components/auth/InputForValidate.tsx
  tailwind.config.ts
Labels: 스타일

#178 style: 메인 소개 캐러셀 반응형 수정
  src/components/main/BrandingCarousel/BrandingCarousel.tsx
  src/components/main/BrandingCarousel/BrandingCarouselItem.tsx
Labels: 스타일

#180 fix: 마이페이지 데스크탑 로딩 ui 추가
  src/components/loading/MypageLoading.tsx
Labels: 새 기능, 스타일

#181 fix: 스티커 움직임 개선, 핸들러 크기 조정
  public/assets/fonts/SUIT-Medium.otf
  public/assets/images/branding/mood-preset-01.png
  src/app/(defaultLayout)/layout.tsx
  src/app/(noLayout)/layout.tsx
  src/app/card/[id]/page.tsx
  src/app/layout.tsx
  src/app/provider.tsx
  src/components/card/MainPhoto.tsx
  src/components/create/StickerInput.tsx
  src/components/create/stickerInput/Sticker.tsx
  src/components/layouts/Header.tsx
  src/components/layouts/Navigation.tsx
  src/hooks/invitation/sticker/useStickerMove.ts
  src/hooks/invitation/sticker/useStickerTransform.ts
  src/hooks/queries/useGetCategorizedStickers.ts
  src/utils/sticker/getImageDimensions.ts
Labels: 버그, 리팩토링

#182 fix: svg 컴포넌트 설정 에러 로그 뜨는 부분 수정, stroke 컬러 적용
  src/components/icons/MessageIcon.tsx
  src/components/icons/PhoneIcon.tsx
Labels: 버그

#194 fix: weddinginfo input 아이콘 누락된 파일 추가
  public/assets/images/icons/expand_more.png
  src/components/ui/SelectBox.tsx
Labels: 스타일

#199 Style/디자인 QA 반영: 하단 퀵링크, AuthForm 에러메세지
  src/components/auth/InputForValidate.tsx
  src/components/ui/FixedQuickLink.tsx
Labels: 스타일

#205 Fix/button: 청첩장 버튼, FAQ 디자인 수정
  src/components/main/FaqCard.tsx
  src/components/main/MainFaqList.tsx
  src/components/ui/FixedQuickLink.tsx
Labels: 스타일

#203 style: 계좌 정보 입력란 데스크탑 시안 적용
  src/components/create/AccountInput.tsx
Labels: 스타일

#208 Style: 청첩장 갤러리, 인사말, 메인사진 폼 데스크탑 시안 반영
  src/components/create/GalleryInput.tsx
  src/components/create/GreetingInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/gallery/GalleryButton.tsx
Labels: 스타일

#206 style: 메인화면 꾸미기 데스크탑 padding값 추가
  src/app/(createCardLayout)/create/card/page.tsx
  src/components/create/DesktopInputForm.tsx
  src/components/create/MainViewInput.tsx
Labels: 스타일

#207 style:review,mypage수정, 카운트 추가
  src/app/(defaultLayout)/mypage/page.tsx
  src/components/icons/HeartIcon.tsx
  src/components/icons/SmileyHappy.tsx
  src/components/mypage/LogoutButton.tsx
  src/components/mypage/MyInvitationCard.tsx
  src/components/mypage/MyPageNavigatorList.tsx
  src/components/mypage/SetPrivateInvitation.tsx
  src/components/mypage/TogglePrivate.tsx
  src/components/review/ReviewCard.tsx
  src/components/review/ReviewImage.tsx
  src/components/review/ReviewItem.tsx
  src/utils/getContentPreview.ts
Labels: 스타일

#215 Fix/ssg cache: 브라우저 캐시 설정 및 비공개 청첩장 스타일 적용
  next.config.mjs
  public/assets/images/icons/private-card.webp
  src/app/card/[id]/page.tsx
  src/components/card/PrivateCard.tsx
Labels: 새 기능, 스타일

#219 Style/input text color: 제작 페이지 input 태그 스타일 통일
  src/components/create/AccountInput.tsx
  src/components/create/FontInput.tsx
  src/components/create/GreetingInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/create/NavigationDetailInput.tsx
  src/components/create/PersonalInfo.tsx
  src/components/create/WeddingInfoInput.tsx
Labels: 스타일

#210 Feat/compression image (파일 2번 압축)
  package.json
  pnpm-lock.yaml
  src/components/create/GalleryInput.tsx
  src/components/create/MainPhotoInput.tsx
  src/components/create/WeddingInfoInput.tsx
  src/components/mypage/MyInvitationCard.tsx
  src/components/review/ReviewItem.tsx
  src/hooks/auth/useAuthWithEmail.ts
  src/utils/compressImg.ts
Labels: 새 기능

#221 Fix/date format: 날짜 포맷팅 수정, 디자인 qa 반영
  src/components/card/WeddingInfo.tsx
  src/components/create/InvitationBottomSheetFormContainer.tsx
  src/components/create/WeddingInfoInput.tsx
  src/hooks/invitation/useGetValidatedDay.ts
  src/utils/date/formatDate.ts
  src/utils/date/getDayOfWeek.ts
Labels: 새 기능, 스타일

#222 Style/design qa text: 디자인 qa 반영
  src/components/card/Greeting.tsx
  src/components/create/InvitationBottomSheetFormContainer.tsx
  src/components/create/StickerInput.tsx
  src/components/review/ReviewWriteButton.tsx
  src/utils/createCardFormHeightMapper.ts
Labels: 스타일

#226 Doc/read me: 리드미 아티클 부분 제외 상세내용 완성
  README.md
Labels: 문서

#243 Fix/mobile safari date: 모바일 사파리 Date 에러 대응
  package.json
  pnpm-lock.yaml
  src/components/card/WeddingInfo.tsx
  src/hooks/invitation/useGetValidatedDay.ts
  src/utils/date/formatDate.ts
  src/utils/date/getDayOfWeek.ts
Labels: 버그

#247 Style/desktop design qa: 예식정보, 컬러팔레트 데스크탑 디자인 QA 반영 / 메인 캐러셀 시작 위치 조정
  src/components/create/ColorPalette.tsx
  src/components/create/FontInput.tsx
  src/components/create/WeddingInfoInput.tsx
  src/components/main/BrandingCarousel/BrandingCarousel.tsx
  src/hooks/ui/useCarousel.ts
Labels: 스타일

#253 Fix/revalidate path await: 청첩장 완성 revalidateInvitation 함수 추가
  src/components/mypage/TogglePrivate.tsx
  src/hooks/create/useInvitationFormActions.ts
  src/utils/revalidateInvitation.ts
Labels: 버그

#256 style: 모바일 form shadow 추가
  src/components/create/InvitationBottomSheetFormContainer.tsx
Labels: 스타일

#259 fix: 데스크탑에서 퍼플 그레이 안 눌러지는 현상 수정
  src/components/create/DesktopInputForm.tsx
Labels: 버그
